import Head from "next/head";
import Footer from "../../components/Footer";
import MobileHeader from "../../components/mobileHeader/MobileHeader";
import NewHeader from "../../components/header/NewHeader";
import VipperBryn from "../../components/priser/VipperBryn";

export default function vipperOgBryn() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty | Håndpleie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:inline hidden">
        <NewHeader />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <VipperBryn />
      <Footer />
    </div>
  );
}
