import Footer from "../components/Footer";
import Header from "../components/Header";

export default function bookTime() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Price List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <h1>Booking</h1>
      <Footer />
    </div>
  );
}
