import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function contact() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Cantacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Contact</h1>
      <Footer />
    </div>
  );
}
