import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Klippekort from "../components/Klippekort";
import Gavekort from "../components/Gavekort";

export default function giftcard() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Giftcard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Gavekort />
      <Footer />
    </div>
  );
}
