import Head from "next/head";
import Header from "../components/Header";
import HeaderFixed from "../components/header/HeaderFixed";
import MobileHeader from "../components/mobileHeader/MobileHeader";
import Footer from "../components/Footer";
import InstaFeed from "../components/InstaFeed";
import BannerTwo from "../components/banner/BannerTwo";
import NewHeader from "../components/test/NewHeader";
// import ImageSlider from "../components/slider/ImageSlider";
// import { SliderData } from "../components/slider/SliderData";

export default function IndexPage() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:inline">
        <NewHeader />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      {/*<InfoCovid />*/}
      <BannerTwo />
      <InstaFeed />
      <Footer />
    </div>
  );
}

// <ImageSlider slides={SliderData} />
