import Head from "next/head";
import BannerTwo from "../components/banner/BannerTwo";
import InstagramFeed from "../components/widgets/InstagramFeed";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Enga Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BannerTwo />
        <InstagramFeed />
      </main>
    </>
  );
}
