import Head from "next/head";
import MobileHeader from "../components/mobileHeader/MobileHeader";
import Footer from "../components/Footer";
import InstaFeed from "../components/InstaFeed";
import BannerTwo from "../components/banner/BannerTwo";
import NewHeader from "../components/header/NewHeader";
import WorkWithUs from "../components/banner/WorkWithUs";
// import InstagramFeed from "../components/widgets/InstagramFeed";

export default function IndexPage() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:inline">
        <NewHeader />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <div className="">
        <BannerTwo />
      </div>
      {/* <WorkWithUs /> */}
      {/* <InstagramFeed /> */}
      <Footer />
    </div>
  );
}
