import Head from "next/head";
import Footer from "../components/Footer";
import Paraffin from "../components/treatments/Paraffin";
import HeaderFixed from "../components/header/HeaderFixed";
import MobileHeader from "../components/mobileHeader/MobileHeader";
import NewHeader from "../components/header/NewHeader";
import XLParaffin from "../components/treatments/XLParaffin";

export default function paraffin() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty | Parafin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:inline hidden">
        <NewHeader />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <div className="xl:hidden">
        <Paraffin />
      </div>
      <div className="xl:inline hidden">
        <XLParaffin />
      </div>
      <Footer />
    </div>
  );
}
