import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import PriceList from "../components/PriceList";

export default function pricelist() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Price List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PriceList />
      <Footer />
    </div>
  );
}
