import Head from "next/head";
import Footer from "../components/Footer";
import Klippekort from "../components/Klippekort";
import HeaderFixed from "../components/header/HeaderFixed";
import MobileHeader from "../components/mobileHeader/MobileHeader";

export default function seasonTicket() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty | Klippekort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:inline">
        <HeaderFixed />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <Klippekort />
      <Footer />
    </div>
  );
}
