import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function seasonTicket() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Season Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex justify-center items-center h-[500px] text-5xl">
        Vil være tilgjengelig veldig snart!
      </div>
      <Footer />
    </div>
  );
}
