import Head from "next/head";
import Footer from "../components/Footer";
import Waxing from "../components/treatments/Waxing";
import HeaderFixed from "../components/header/HeaderFixed";
import MobileHeader from "../components/mobileHeader/MobileHeader";

export default function waxing() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Waxing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:inline">
        <HeaderFixed />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <Waxing />
      <Footer />
    </div>
  );
}
