import Head from "next/head";
import Footer from "../components/Footer";
import Waxing from "../components/treatments/Waxing";
import HeaderFixed from "../components/header/HeaderFixed";
import MobileHeader from "../components/mobileHeader/MobileHeader";
import NewHeader from "../components/header/NewHeader";
import XLWaxing from "../components/treatments/XLWaxing";

export default function waxing() {
  return (
    <div className="selection:bg-[gold]">
      <Head>
        <title>Enga Beauty | Voksing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:inline">
        <NewHeader />
      </div>
      <div className="lg:hidden">
        <MobileHeader />
      </div>
      <div className="xl:hidden">
        <Waxing />
      </div>
      <div className="hidden xl:inline">
        <XLWaxing />
      </div>
      <Footer />
    </div>
  );
}
